config = {
    "batch_size": 8,
    "context_window": 1024,
    "d_head": 2,
    "d_mlp": 128,
    "d_model": 32,
    "d_vocab": 50257,
    "dataset": "roneneldan/TinyStories",
    "epochs": 1,
    "initialized_std_range": 0.02,
    "layer_norm_epsilon": 1e-5,
    "num_blocks": 4,
    "num_heads": 16,
    "max_batches_per_epoch": 1e5,
    "test_size": 1000,
    "learning_rate": 1e-3,
    "weight_decay": 1e-2,
}
