config = {
    "num_sequences_per_batch": 8,
    "context_window": 256,
    "d_head": 8,
    "d_mlp": 1024,
    "d_embedding": 256,
    "d_vocab": 50257,
    "dataset": "roneneldan/TinyStories",
    "epochs": 3,
    "initialized_std_range": 0.02,
    "layer_norm_epsilon": 1e-5,
    "num_blocks": 4,
    "num_heads": 4,
    "max_batches_per_epoch": None,
    "test_size": 1,
    "learning_rate": 3e-4,
    "weight_decay": 1e-4,
    "limited_dataset_size": None,
}
